pentaho/pdi-platform-utils-plugin

ivy.xml, src/org/pentaho/di/baserver/utils/inspector/Inspector.java, src/org/pentaho/di/baserver/utils/inspector/WadlParser.java, test-res/wadl.xml, test-src/org/pentaho/di/baserver/utils/inspector/EndpointTest.java, test-src/org/pentaho/di/baserver/utils/inspector/InspectorTest.java, test-src/org/pentaho/di/baserver/utils/inspector/QueryParamTest.java, test-src/org/pentaho/di/baserver/utils/inspector/WadlParserTest.java
=> [TEST] - Added tests for org.pentaho.di.baserver.utils.inspector package

ivy.xml, src/org/pentaho/di/baserver/utils/inspector/WadlParser.java, test-src/org/pentaho/di/baserver/utils/CallEndpointMetaTest.java, test-src/org/pentaho/di/baserver/utils/GetSessionVariableMetaTest.java, test-src/org/pentaho/di/baserver/utils/SetSessionVariableMetaTest.java, test-src/org/pentaho/di/baserver/utils/inspector/EndpointTest.java, test-src/org/pentaho/di/baserver/utils/inspector/InspectorTest.java, test-src/org/pentaho/di/baserver/utils/inspector/QueryParamTest.java, test-src/org/pentaho/di/baserver/utils/inspector/WadlParserTest.java
new unit tests are written to improve coverage
@pamval @diogofscmariano please review
=> [TEST] - unit tests written

test-src/org/pentaho/di/baserver/utils/CallEndpointMetaTest.java
=> [TEST] - fix failing CallEndpointMetaTest.setDefault

test-src/org/pentaho/di/baserver/utils/inspector/InspectorTest.java
=> [TEST] - fix test - clean Inspector at start

ivy.xml, src/org/pentaho/di/baserver/utils/CallEndpointStep.java, src/org/pentaho/di/baserver/utils/inspector/Inspector.java, src/org/pentaho/di/baserver/utils/web/HttpConnectionHelper.java, src/org/pentaho/di/baserver/utils/web/InternalHttpServletRequest.java, test-src/org/pentaho/di/baserver/utils/web/HttpConnectionHelperTest.java
=> [TEST] - Added unit tests for HttpConnectionHelper

src/org/pentaho/di/baserver/utils/web/HttpConnectionHelper.java, test-src/org/pentaho/di/baserver/utils/web/HttpConnectionHelperTest.java
@diogofscmariano please review
=> [BACKLOG-2906] - Url parameters not encoded

ivy.xml, src/org/pentaho/di/baserver/utils/CallEndpointStep.java, src/org/pentaho/di/baserver/utils/inspector/Inspector.java, src/org/pentaho/di/baserver/utils/web/HttpConnectionHelper.java, test-src/org/pentaho/di/baserver/utils/web/HttpConnectionHelperTest.java
added support for get, post, put, delete, head, options
@diogofscmariano
=> [BACKLOG-2907] - Not using Bypass Authentication forces GET Method

src/org/pentaho/di/baserver/utils/widgets/BrowserBuilder.java, src/org/pentaho/di/baserver/utils/widgets/callEndpointTabs/EndpointTab.java
=> [BACKLOG-2452] - Update Documentation Box to display html code styled

src/org/pentaho/di/baserver/utils/CallEndpointStep.java
=> [CLEANUP] - don't search for field in InputRowMeta if fieldName is empty

src/org/pentaho/di/baserver/utils/CallEndpointMeta.java, src/org/pentaho/di/baserver/utils/GetSessionVariableMeta.java, src/org/pentaho/di/baserver/utils/SetSessionVariableMeta.java, src/org/pentaho/di/baserver/utils/messages/messages_en_US.properties, src/org/pentaho/di/baserver/utils/widgets/callEndpointTabs/EndpointTab.java
[BACKLOG-2456] - Updated Messages. Fixed dropdown update bugs
@marcovala please review
=> [BACKLOG-2456] - Added documentation links

src/org/pentaho/di/baserver/utils/BAServerCommonDialog.java, src/org/pentaho/di/baserver/utils/CallEndpointDialog.java, src/org/pentaho/di/baserver/utils/GetSessionVariableDialog.java, src/org/pentaho/di/baserver/utils/SetSessionVariableDialog.java
=> [BACKLOG-2454] - Updated icons inside steps to use svg

src/org/pentaho/di/baserver/utils/widgets/callEndpointTabs/EndpointTab.java
=> [BACKLOG-2456] - Fixed bug with messages

samples/callEndpointExample.ktr, samples/getRolesForUser.ktr, samples/listRepositoryFiles.ktr, samples/setSessionVariable.ktr, src/org/pentaho/di/baserver/utils/SetSessionVariableMeta.java
=> [BACKLOG-2452] - Updated samples and fixed issue with meta persistence

src/org/pentaho/di/baserver/utils/BAServerCommonDialog.java, src/org/pentaho/di/baserver/utils/SetSessionVariableDialog.java, src/org/pentaho/di/baserver/utils/widgets/GroupBuilder.java, src/org/pentaho/di/baserver/utils/widgets/callEndpointTabs/EndpointTab.java, src/org/pentaho/di/baserver/utils/widgets/callEndpointTabs/OutputFieldsTab.java, src/org/pentaho/di/baserver/utils/widgets/callEndpointTabs/ServerTab.java, src/org/pentaho/di/baserver/utils/widgets/callEndpointTabs/Tab.java
=> [BACKLOG-2452] - Fixed typo. Reviewed dropdown update flow.

src/org/pentaho/di/baserver/utils/CallEndpointMeta.java, src/org/pentaho/di/baserver/utils/GetSessionVariableMeta.java, src/org/pentaho/di/baserver/utils/SetSessionVariableMeta.java, src/org/pentaho/di/baserver/utils/messages/messages_en_US.properties
=> [BACKLOG-24540] - Updated steps location. Fixed help link

build.xml, package-res/settings.xml, src/org/pentaho/di/baserver/utils/SetSessionVariableData.java
=> [BACKLOG-3102] - Changed the blacklist settings location

src/org/pentaho/di/baserver/utils/CallEndpointMeta.java, src/org/pentaho/di/baserver/utils/GetSessionVariableMeta.java, src/org/pentaho/di/baserver/utils/SetSessionVariableMeta.java, src/org/pentaho/di/baserver/utils/messages/messages_en_US.properties
=> [BACKLOG-2846] - Updated documentation links

build.properties, src/org/pentaho/di/baserver/utils/SetSessionVariableData.java
=> [BACKLOG-3346] - Updated project folder name and settings.xml reference

src/org/pentaho/di/baserver/utils/SetSessionVariableDialog.java
=> [BACKLOG-3349] - Fixed column value load

src/org/pentaho/di/baserver/utils/CallEndpointDialog.java
@pamval @mdamour1976 please review
=> [BACKLOG-3430] - Updated Height of Call Endpoint Step for Linux

ivy.xml
=> [BACKLOG-3756] Update projects with the pentaho vfs version to version 2

build.properties
with the build teams property list.
@lucboudreau
=> [CLEANUP]  Removing unused property that is inconsistent

test-src/org/pentaho/di/baserver/utils/GetSessionVariableMetaTest.java, test-src/org/pentaho/di/baserver/utils/GetSessionVariableStepTest.java, test-src/org/pentaho/di/baserver/utils/SetSessionVariableMetaTest.java, test-src/org/pentaho/di/baserver/utils/widgets/BrowserBuilderTest.java, test-src/org/pentaho/di/baserver/utils/widgets/ButtonBuilderTest.java, test-src/org/pentaho/di/baserver/utils/widgets/GroupBuilderTest.java, test-src/org/pentaho/di/baserver/utils/widgets/LabelBuilderTest.java, test-src/org/pentaho/di/baserver/utils/widgets/TextAreaBuilderTest.java, test-src/org/pentaho/di/baserver/utils/widgets/TextBoxBuilderTest.java, test-src/org/pentaho/di/baserver/utils/widgets/TextVarBuilderTest.java, test-src/org/pentaho/di/baserver/utils/widgets/WidgetBuilderMock.java, test-src/org/pentaho/di/baserver/utils/widgets/WidgetBuilderTest.java
- Increased unit test coverage for the builders;
- Applied CheckStyle to existing classes;
=> [BACKLOG-5384, TEST, CLEANUP] - Increase unit test coverage

src/org/pentaho/di/baserver/utils/inspector/Inspector.java
@mbatchelor, @mkambol, could you please take a look?
=> [PPP-3506] - XXE Security Vulnerability in xml parsers

ivy.xml, src/org/pentaho/di/baserver/utils/inspector/Inspector.java, src/org/pentaho/di/baserver/utils/web/HttpConnectionHelper.java, src/org/pentaho/di/baserver/utils/widgets/callEndpointTabs/ServerTab.java, test-src/org/pentaho/di/baserver/utils/inspector/InspectorTest.java, test-src/org/pentaho/di/baserver/utils/web/HttpConnectionHelperTest.java
Reverts pentaho/pdi-platform-utils-plugin#79
=> Revert "[PPP-3735] - Use of vulnerable component httpclient-3.0.1.jar, common…"

assemblies/plugin/pom.xml, assemblies/pom.xml, core/pom.xml, pom.xml
@pentaho/2-1b @smaring Please review.
=> [CLEANUP] Update the version to 8.1-SNAPSHOT

assemblies/plugin/pom.xml, assemblies/pom.xml, core/pom.xml, pom.xml
@pentaho/2-1b @smaring Please review.
=> [CLEANUP] Update maven parent pom to be the community edition.

pom.xml
@pentaho-svigneri Please review. This fixes issues created by commit 44ffd8e0e5.
=> [TEST] - Add missing test dependencies on commons-lang, slf4j, and mockito.

core/pom.xml, pom.xml
This is one of a series of PRs. See pentaho/maven-parent-poms#70 for the complete list and more details. **Do not merge until further notice!**
@graimundo
=> [PPP-4182] Use of vulnerable component dom4j-1.6.1.jar  CVE-2018-1000632

pom.xml
Reverts pentaho/pdi-platform-utils-plugin#106
=> Revert "[BACKLOG-35047] Update dependency for sping framework 5.3.3 upgrade."

core/src/main/java/org/pentaho/di/baserver/utils/web/HttpConnectionHelper.java, core/src/main/java/org/pentaho/di/baserver/utils/web/InternalHttpServletRequest.java, core/src/main/java/org/pentaho/di/baserver/utils/web/InternalHttpServletResponse.java, core/src/main/java/org/pentaho/di/baserver/utils/web/ServletInputStreamWrapper.java, core/src/main/java/org/pentaho/di/baserver/utils/web/ServletOutputStreamWrapper.java, core/src/test/java/org/pentaho/di/baserver/utils/web/HttpConnectionHelperTest.java, core/src/test/java/org/pentaho/di/baserver/utils/web/InternalHttpServletRequestTest.java, core/src/test/java/org/pentaho/di/baserver/utils/web/InternalHttpServletResponseTest.java, pom.xml
[BACKLOG-42739]-Upgrading Pdi-platform-utils-plugin from Java Ee to Jakarta EE
[BACKLOG-42739]: https://hv-eng.atlassian.net/browse/BACKLOG-42739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-42739]-Upgrading Pdi-platform-utils-plugin from Java Ee to Jakarta EE

pom.xml
[BACKLOG-44915]-Resolving Review Comments for Pr's related to tomcat
[BACKLOG-44915]: https://hv-eng.atlassian.net/browse/BACKLOG-44915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-44915]-Resolving Review Comments for Pr's related to tomcat
